## What is Convolution?

Convolution is an operation where a small matrix, called a **kernel** or **filter**, slides over an input matrix (image) and performs element-wise multiplication and summation to produce an output matrix. This can be used to detect features like edges, corners, or textures in an image.



### Explanation of the code
1. **Kernel flipping**
    - Before the convolutional operation, we need to flip the kernel both horizontally and vertically to ensure that the convolution adheres to its mathematical definition
2. **Adding padding**
    - To ensure that the spatial dimensions of the image are preserved, extra pixels around the border of the image are added. This can help in reducing the loss of information
3. **Sliding the kernel**
    - We iterate over each pixel in the image and extract a region of interest of the same size as the kernel
4. **Element-wise Multiplication**
    - The region and kernel are multiplied element-wise, and the result is summed to calculate the output pixel value

In [11]:
import numpy as np

def convolve2d(image, kernel):
    """
    Perform a 2D convolution on an image using a given kernel.
    
    Args:
    - image (numpy.ndarray): Input image (grayscale).
    - kernel (numpy.ndarray): Convolution kernel (filter).
    
    Returns:
    - result (numpy.ndarray): Convolved image.
    """
    # Flip the kernel (required for convolution)
    kernel = np.flipud(np.fliplr(kernel))  
    
    # Get the dimensions of the image and kernel
    image_height, image_width = image.shape
    kernel_height, kernel_width = kernel.shape
    
    # Calculate padding size
    pad_height = kernel_height // 2
    pad_width = kernel_width // 2
    
    # Pad the image with zeros (to keep the output size the same as input)
    padded_image = np.pad(image, ((pad_height, pad_height), (pad_width, pad_width)), mode='constant')
    print(padded_image)
    # Create an output array with the same shape as the image
    result = np.zeros_like(image)
    
    # Perform the convolution
    for i in range(image_height):
        for j in range(image_width):
            # Extract the region of interest
            region = padded_image[i:i + kernel_height, j:j + kernel_width]
            print(region)
            # Perform element-wise multiplication and sum
            result[i, j] = np.sum(region * kernel)
    
    return result

# Example usage
if __name__ == "__main__":
    
    # Sample grayscale image (3x3 matrix)
    image = np.array([[1, 2, 3, 5, 7, 9],
                      [6, 7, 8, 9, 1, 2],
                      [11, 12, 13, 15, 16, 20]])
    
    # Example kernel (3x3 Sobel horizontal filter)
    kernel = np.array([[-1, -2, -3, -4],
                       [ 0,  0, 0, 0],
                       [ 1,  2, 3, 4]])
    
    # Perform convolution
    convolved_image = convolve2d(image, kernel)
    
    print("Original Image:\n", image)
    print("\nKernel:\n", kernel)
    print("\nConvolved Image:\n", convolved_image)

[[ 0  0  0  0  0  0  0  0  0  0]
 [ 0  0  1  2  3  5  7  9  0  0]
 [ 0  0  6  7  8  9  1  2  0  0]
 [ 0  0 11 12 13 15 16 20  0  0]
 [ 0  0  0  0  0  0  0  0  0  0]]
[[0 0 0 0]
 [0 0 1 2]]
[[0 0 0 0]
 [0 1 2 3]]
[[0 0 0 0]
 [1 2 3 5]]
[[0 0 0 0]
 [2 3 5 7]]
[[0 0 0 0]
 [3 5 7 9]]
[[0 0 0 0]
 [5 7 9 0]]
[[0 0 1 2]
 [0 0 6 7]]
[[0 1 2 3]
 [0 6 7 8]]
[[1 2 3 5]
 [6 7 8 9]]
[[2 3 5 7]
 [7 8 9 1]]
[[3 5 7 9]
 [8 9 1 2]]
[[5 7 9 0]
 [9 1 2 0]]
[[ 0  0  6  7]
 [ 0  0 11 12]]
[[ 0  6  7  8]
 [ 0 11 12 13]]
[[ 6  7  8  9]
 [11 12 13 15]]
[[ 7  8  9  1]
 [12 13 15 16]]
[[ 8  9  1  2]
 [13 15 16 20]]
[[ 9  1  2  0]
 [15 16 20  0]]
Original Image:
 [[ 1  2  3  5  7  9]
 [ 6  7  8  9  1  2]
 [11 12 13 15 16 20]]

Kernel:
 [[-1 -2 -3 -4]
 [ 0  0  0  0]]

Convolved Image:
 [[  -4  -10  -21  -34  -50  -59]
 [ -19  -40  -70  -71  -63  -43]
 [ -34  -70 -121 -133 -149 -148]]
